# Generated by Django 5.0.7 on 2024-07-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Female'), (2, 'Male')], default=1),
        ),
    ]
