# Generated by Django 5.0.7 on 2024-07-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dad_occup',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='father_edu_level',
            field=models.IntegerField(choices=[(1, 'None formal'), (2, 'Primary'), (3, 'Secondary'), (4, 'Tertiary')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='mother_edu_level',
            field=models.IntegerField(choices=[(1, 'None formal'), (2, 'Primary'), (3, 'Secondary'), (4, 'Tertiary')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='mum_occup',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='religion',
            field=models.IntegerField(choices=[(1, 'Christianity'), (2, 'Islam'), (3, 'Traditional African Religion'), (4, 'Atheist')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='ses_parents',
            field=models.CharField(choices=[(1, 'Upper class – professional'), (2, 'Upper middle class - managerial'), (3, 'Lower middle class clerical/skilled'), (4, 'Upper lower class – semi-skilled'), (5, 'Lower class – unskilled')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='tribe',
            field=models.CharField(choices=[('Igbo', 1), ('Hausa', 2), ('Yoruba', 3)], default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('Male', 'Male')], default=0, max_length=100),
        ),
    ]
