# Generated by Django 5.0.7 on 2024-07-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_dad_occup_question_father_edu_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ses_parents',
            field=models.IntegerField(choices=[(1, 'Upper class – professional'), (2, 'Upper middle class - managerial'), (3, 'Lower middle class clerical/skilled'), (4, 'Upper lower class – semi-skilled'), (5, 'Lower class – unskilled')], default=0, max_length=50),
        ),
    ]
